# Generated by Django 5.2.7 on 2025-10-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='member',
            new_name='user',
        ),
    ]
