# Generated by Django 5.2.7 on 2025-10-26 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_member_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='daily',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=20)),
                ('last_date', models.DateTimeField()),
                ('next_date', models.DateTimeField()),
                ('is_choice', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.task')),
            ],
        ),
    ]
