# Generated by Django 5.2.7 on 2025-10-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_maintenance_created_at_maintenance_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
