# Generated by Django 5.2.7 on 2025-11-15 05:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_maintenance_created_at_alter_task_created_at_and_more'),
        ('user', '0008_remove_users_avatar_url_users_avatar_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.maintenance'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.tasklist'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='last_date',
            field=models.DateTimeField(verbose_name='前回実施日'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='next_date',
            field=models.DateTimeField(verbose_name='次回予定日'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='target_name',
            field=models.CharField(max_length=20, verbose_name='メンテナンス名'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.users'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=0, help_text='ビットフラグで複数曜日を表現(例: 月・水・金 = 1+4+16=21)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(127)], verbose_name='頻度(曜日)'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='homemaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_lists', to='user.users', verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task_name',
            field=models.CharField(max_length=50, verbose_name='家事名'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='1=簡単, 5=大変', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='重み'),
        ),
    ]
