# Generated by Django 5.2.7 on 2025-11-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_maintenance_task_remove_tasklist_task_and_more'),
        ('user', '0008_remove_users_avatar_url_users_avatar_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='homemaker',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='homemakers',
            field=models.ManyToManyField(blank=True, related_name='maintenance_task_lists', to='user.users', verbose_name='担当者'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='homemakers',
            field=models.ManyToManyField(blank=True, related_name='task_lists', to='user.users', verbose_name='担当者'),
        ),
    ]
