# Generated by Django 5.2.7 on 2025-10-17 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joincode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='relation_to_admin',
            field=models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='joincode',
            name='code8',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
    ]
