# Generated by Django 5.2.7 on 2025-10-17 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_joincode_created_at_member_relation_to_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joincode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
