# Generated by Django 5.2.7 on 2025-10-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_member_created_at_member_nickname_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='joincode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
