# Generated by Django 5.2.7 on 2025-10-24 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_member_task_user'),
        ('user', '0005_joincode_used_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Users',
        ),
    ]
