# Generated by Django 5.2.7 on 2025-10-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_member_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joincode',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
