# Generated by Django 5.2.7 on 2025-11-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_joincode_revoked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='users',
            name='avatar_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
